title: "Columbia AMPS"
email: amps@columbia.edu
description: "The Association of Applied Math, Applied Physics, Materials Science, and Medical Physics"
url: "https://columbia-amps.github.io"
baseurl: ""
timezone: America/New_York

plugins:
  - jekyll-feed

# permalink for posts
permalink: /blog/:year/:month/:day/:title/
