version: "3.9"
services:
  site:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /site
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/site
      - bundle-cache:/site/vendor/bundle
    environment:
      - JEKYLL_ENV=development
volumes:
  bundle-cache:
